HERUGLON_UNKNOWN = 0
HERUGLON_VERB = 1
HERUGLON_VERB_SUBJUNCTIVE = 2
HERUGLON_PREPOSITION = 3
HERUGLON_NUMBER = 4
HERUGLON_NUMBER_PRETTY = 5

HERUGLON_NAMES = {
    HERUGLON_UNKNOWN: "Unknown",
    HERUGLON_VERB: "Verb",
    HERUGLON_VERB_SUBJUNCTIVE: "Verb Subjunctive",
    HERUGLON_PREPOSITION: "Preposition",
    HERUGLON_NUMBER: "Number",
    HERUGLON_NUMBER_PRETTY: "Pretty Number",
}